server:
  port: 8002

spring:
  devtools:
    restart:
      enabled: true
  application:
    name: cloud-provider-payment8002
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: liaowh123

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.liaowh.springcloud.entities    # 所有Entity别名类所在包


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      # 集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true     #访问路径可以显示IP地址